### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by RetroGamer02** [RetroGamer02/gnuboy-3ds#1]
- [x] Fix Occasional Input oddities.
- [ ] Add Auto-Sram/RTC Saving
- [x] Investigate and fix cia build issues.
- [ ] Fix invalid opcode when switching from gbc to dmg when using bios file.
- [x] Add saving for video mode option.
- [ ] Replace SDL with 3DS code.

**Comment by RetroGamer02** [comment]
Auto Sram/RTC Saving lags when done so needs more work.
